# This file is machine-generated - editing it directly is not advised

manifest_format = "2.0"

[[deps.HexagonalArrays]]
git-tree-sha1 = "2f23334790067b7dc2bdf7f3677a92980011f784"
repo-rev = "v0.1.3"
repo-url = "https://github.com/a-r-n-o-l-d/HexagonalArrays.jl"
uuid = "e7428160-d03f-46d2-b46d-0a3a5554cbe0"
version = "0.1.3"
