name = "HexagonalNeighborhoods"
uuid = "cbba3797-e0c9-4625-9eb1-9743a1780c4c"
authors = ["Arnold"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
